# NumPy & Pandas — 20-Minute Demo
A hands-on tour of the two most essential Python data-science libraries.

| # | Topic | Approx. Time |
|---|-------|-------------|
| 1 | Import Libraries | 1 min |
| 2 | NumPy — Array Creation & Properties | 3 min |
| 3 | NumPy — Indexing & Slicing | 2 min |
| 4 | NumPy — Math & Statistics | 2 min |
| 5 | Pandas — Series & DataFrame Creation | 3 min |
| 6 | Pandas — Selection & Filtering | 3 min |
| 7 | Pandas — Data Cleaning | 2 min |
| 8 | Pandas — GroupBy & Aggregation | 2 min |
| 9 | NumPy ↔ Pandas Integration | 2 min |

## 1. Import Required Libraries

In [1]:
import numpy as np
import pandas as pd

print(f"NumPy  version: {np.__version__}")
print(f"Pandas version: {pd.__version__}")

NumPy  version: 2.4.1
Pandas version: 3.0.0

## 2. NumPy — Array Creation & Basic Properties

Key factory functions:
- `np.array()` — from Python list/tuple  
- `np.zeros()` / `np.ones()` — filled arrays  
- `np.arange()` — evenly spaced by step  
- `np.linspace()` — evenly spaced by count  

Important attributes: **shape**, **dtype**, **ndim**, **size**

In [12]:
# --- 1D array from a list ---
a1 = np.array([10, 20, 30, 40, 50])
print("1D array:", a1)
print("  shape:", a1.shape, "| dtype:", a1.dtype, "| ndim:", a1.ndim)

# --- 2D array (matrix) ---
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])
print("\n2D array:\n", a2)
print("  shape:", a2.shape, "| size:", a2.size)

# --- Filled arrays ---
print("\nzeros(3,4):\n", np.zeros((3, 4)))
print("\nones(2,3) * 7:\n", np.ones((2, 3)) * 7)

1D array: [10 20 30 40 50]
  shape: (5,) | dtype: int64 | ndim: 1

2D array:
 [[1 2 3]
 [4 5 6]]
  shape: (2, 3) | size: 6

zeros(3,4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

ones(2,3) * 7:
 [[7. 7. 7.]
 [7. 7. 7.]]

## 3. NumPy — Indexing & Slicing

```
arr[start : stop : step]   # slicing syntax
arr[row, col]              # 2D indexing
arr[arr > value]           # boolean mask
```

In [13]:
arr = np.arange(10, 60, 10)          # [10 20 30 40 50]
print("Array:", arr)

# 1D indexing
print("arr[0]:", arr[0])            # first element
print("arr[-1]:", arr[-1])          # last element
print("arr[1:4]:", arr[1:4])        # slice
print("arr[::2]:", arr[::2])        # every other element

# 2D indexing
mat = np.arange(1, 13).reshape(3, 4)
print("\nMatrix:\n", mat)
print("mat[1, 2]:", mat[1, 2])      # row 1, col 2
print("mat[:, 1]:", mat[:, 1])      # entire column 1
print("mat[0:2, 1:3]:\n", mat[0:2, 1:3])  # sub-matrix

Array: [10 20 30 40 50]
arr[0]: 10
arr[-1]: 50
arr[1:4]: [20 30 40]
arr[::2]: [10 30 50]

Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
mat[1, 2]: 7
mat[:, 1]: [ 2  6 10]
mat[0:2, 1:3]:
 [[2 3]
 [6 7]]

## 4. NumPy — Mathematical Operations & Statistics

NumPy operations are **element-wise** by default.  
**Broadcasting** lets arrays of different shapes work together without copying data.

In [14]:
x = np.array([1.0, 4.0, 9.0, 16.0, 25.0])
y = np.array([2.0, 2.0, 3.0,  4.0,  5.0])

# Element-wise arithmetic
print("x + y  :", x + y)
print("x * y  :", x * y)
print("x / y  :", x / y)
print("sqrt(x):", np.sqrt(x))

# Broadcasting — add a scalar to every element
print("\nx + 100:", x + 100)

# Aggregation / statistics
grades = np.array([72, 85, 91, 60, 78, 95, 88, 74])
print("\nStudent grades:", grades)
print(f"  Mean  : {np.mean(grades):.2f}")
print(f"  Std   : {np.std(grades):.2f}")
print(f"  Min   : {np.min(grades)}")
print(f"  Max   : {np.max(grades)}")
print(f"  Median: {np.median(grades)}")

x + y  : [ 3.  6. 12. 20. 30.]
x * y  : [  2.   8.  27.  64. 125.]
x / y  : [0.5 2.  3.  4.  5. ]
sqrt(x): [1. 2. 3. 4. 5.]

x + 100: [101. 104. 109. 116. 125.]

Student grades: [72 85 91 60 78 95 88 74]
  Mean  : 80.38
  Std   : 10.83
  Min   : 60
  Max   : 95
  Median: 81.5

## 5. Pandas — Series & DataFrame Creation

| Structure | Analogy | Creation |
|-----------|---------|----------|
| `Series` | Labeled 1-D array | `pd.Series(data)` |
| `DataFrame` | Spreadsheet table | `pd.DataFrame(data)` |

In [15]:
# --- Series ---
temperatures = pd.Series([22.5, 19.0, 25.3, 28.1, 17.8],
                         index=["Mon", "Tue", "Wed", "Thu", "Fri"],
                         name="Temperature (°C)")
print("Series:\n", temperatures)
print("\nIndexed value (Wed):", temperatures["Wed"])

Series:
 Mon    22.5
Tue    19.0
Wed    25.3
Thu    28.1
Fri    17.8
Name: Temperature (°C), dtype: float64

Indexed value (Wed): 25.3

In [16]:

# --- DataFrame from a dictionary ---
sales_data = {
    "Product":  ["Widget A", "Widget B", "Gadget X", "Gadget Y", "Widget A", "Gadget X"],
    "Region":   ["North", "South", "North", "East", "East", "South"],
    "Units":    [120, 85, 200, 150, 95, 175],
    "Price":    [29.99, 49.95, 99.00, 79.50, 29.99, 99.00],
    "Month":    ["Jan", "Jan", "Jan", "Feb", "Feb", "Feb"],
}
df = pd.DataFrame(sales_data)
df["Revenue"] = df["Units"] * df["Price"]      # derived column

print("\nDataFrame head:")
display(df.head())

print("\nShape:", df.shape)
print("\nColumn dtypes:\n", df.dtypes)
print("\nDescriptive stats:")
display(df.describe())

DataFrame head:

    Product Region  Units  Price Month   Revenue
0  Widget A  North    120  29.99   Jan   3598.80
1  Widget B  South     85  49.95   Jan   4245.75
2  Gadget X  North    200  99.00   Jan  19800.00
3  Gadget Y   East    150  79.50   Feb  11925.00
4  Widget A   East     95  29.99   Feb   2849.05

Shape: (6, 6)

Column dtypes:
 Product        str
Region         str
Units        int64
Price      float64
Month          str
Revenue    float64
dtype: object

Descriptive stats:

           Units      Price       Revenue
count    6.00000   6.000000      6.000000
mean   137.50000  64.571667   9957.266667
std     45.46977  32.246091   7464.758986
min     85.00000  29.990000   2849.050000
25%    101.25000  34.980000   3760.537500
50%    135.00000  64.725000   8085.375000
75%    168.75000  94.125000  15975.000000
max    200.00000  99.000000  19800.000000

## 6. Pandas — Data Selection & Filtering

| Method | Purpose |
|--------|----------|
| `df["col"]` | Select single column |
| `df[["c1", "c2"]]` | Select multiple columns |
| `df.loc[label]` | Row by **label** |
| `df.iloc[index]` | Row by **integer position** |
| `df[mask]` | Filter rows by boolean condition |

In [22]:
display(df.head())

    Product Region  Units  Price Month   Revenue
0  Widget A  North    120  29.99   Jan   3598.80
1  Widget B  South     85  49.95   Jan   4245.75
2  Gadget X  North    200  99.00   Jan  19800.00
3  Gadget Y   East    150  79.50   Feb  11925.00
4  Widget A   East     95  29.99   Feb   2849.05

In [23]:
# Column selection
print("Units column:\n", df["Units"].values)
print("\nProduct , Revenue:\n", df[["Product", "Revenue"]])

Units column:
 [120  85 200 150  95 175]

Product , Revenue:
     Product   Revenue
0  Widget A   3598.80
1  Widget B   4245.75
2  Gadget X  19800.00
3  Gadget Y  11925.00
4  Widget A   2849.05
5  Gadget X  17325.00

In [25]:
df.head()

    Product Region  Units  Price Month   Revenue
0  Widget A  North    120  29.99   Jan   3598.80
1  Widget B  South     85  49.95   Jan   4245.75
2  Gadget X  North    200  99.00   Jan  19800.00
3  Gadget Y   East    150  79.50   Feb  11925.00
4  Widget A   East     95  29.99   Feb   2849.05

In [18]:

# iloc — by integer position
print("\nFirst 3 rows (iloc):\n", df.iloc[:3])
print("\nRow 2, columns 0-2 (iloc):", df.iloc[2, 0:3].values)

First 3 rows (iloc):
     Product Region  Units  Price Month   Revenue
0  Widget A  North    120  29.99   Jan   3598.80
1  Widget B  South     85  49.95   Jan   4245.75
2  Gadget X  North    200  99.00   Jan  19800.00

Row 2, columns 0-2 (iloc): ['Gadget X' 'North' np.int64(200)]

In [24]:
# loc — by label (works best with named index)
df_indexed = df.set_index("Product")
print("\nLocate 'Widget A' rows:\n", df_indexed.loc["Widget A"])

Locate 'Widget A' rows:
          Region  Units  Price Month  Revenue
Product
Widget A  North    120  29.99   Jan  3598.80
Widget A   East     95  29.99   Feb  2849.05

In [20]:
# Boolean / conditional filtering
high_revenue = df[df["Revenue"] > 10_000]
print("\nHigh-revenue rows (> $10 000):\n", high_revenue)

High-revenue rows (> $10 000):
     Product Region  Units  Price Month  Revenue
2  Gadget X  North    200   99.0   Jan  19800.0
3  Gadget Y   East    150   79.5   Feb  11925.0
5  Gadget X  South    175   99.0   Feb  17325.0

In [21]:

north_widgets = df[(df["Region"] == "North") & (df["Product"].str.startswith("Widget"))]
print("\nNorth-region Widgets:\n", north_widgets)

North-region Widgets:
     Product Region  Units  Price Month  Revenue
0  Widget A  North    120  29.99   Jan   3598.8

## 7. Pandas — Data Cleaning & Handling Missing Values

Real-world data is messy. Common steps:
1. **Detect** — `isnull()` / `notnull()`
2. **Drop** — `dropna()`
3. **Fill** — `fillna(value_or_strategy)`
4. **Cast** — `astype()`

In [26]:
import math

dirty = pd.DataFrame({
    "Name":   ["Alice", "Bob", None, "Diana", "Eve"],
    "Age":    [25, None, 30, 22, None],
    "Score":  [88.5, 72.0, None, 95.0, 60.0],
    "Grade":  ["A", "C", "B", None, "D"],
})
print("Raw data:")
display(dirty)

Raw data:

    Name   Age  Score Grade
0  Alice  25.0   88.5     A
1    Bob   NaN   72.0     C
2    NaN  30.0    NaN     B
3  Diana  22.0   95.0   NaN
4    Eve   NaN   60.0     D

In [ ]:
# Detect missing values
print("\nMissing value count:\n", dirty.isnull().sum())
print("\nAny missing per row:\n", dirty.isnull().any(axis=1).values)

Missing value count:
 Name     1
Age      2
Score    1
Grade    1
dtype: int64

Any missing per row:
 [False  True  True  True  True]

In [28]:

# Drop rows with ANY NaN
print("\nAfter dropna():\n", dirty.dropna())

After dropna():
     Name   Age  Score Grade
0  Alice  25.0   88.5     A

In [29]:

# Fill missing values
cleaned = dirty.copy()
cleaned["Age"]   = cleaned["Age"].fillna(cleaned["Age"].median())
cleaned["Score"] = cleaned["Score"].fillna(cleaned["Score"].mean())
cleaned["Name"]  = cleaned["Name"].fillna("Unknown")
cleaned["Grade"] = cleaned["Grade"].fillna("N/A")

print("\nCleaned data:")
display(cleaned)

Cleaned data:

      Name   Age   Score Grade
0    Alice  25.0  88.500     A
1      Bob  25.0  72.000     C
2  Unknown  30.0  78.875     B
3    Diana  22.0  95.000   N/A
4      Eve  25.0  60.000     D

In [30]:

# Type casting
cleaned["Age"] = cleaned["Age"].astype(int)
print("\nAge after astype(int):", cleaned["Age"].tolist())

Age after astype(int): [25, 25, 30, 22, 25]

## 8. Pandas — GroupBy & Aggregation

`groupby()` splits a DataFrame into groups, applies a function, and combines the results — the classic **split-apply-combine** pattern.

In [34]:
region_summary = df.groupby("Region").agg(
    Total_Revenue=("Revenue", "sum"),
    Total_Units=("Units", "sum"),
    Num_Orders=("Product", "count"),
)
print("\nRevenue by Region:")
display(region_summary)

Revenue by Region:

        Total_Revenue  Total_Units  Num_Orders
Region
East         14774.05          245           2
North        23398.80          320           2
South        21570.75          260           2

In [31]:
# Reuse the sales DataFrame from Section 5
print("Original DataFrame:")
display(df)

# Group by Region — total revenue and units per region
region_summary = df.groupby("Region").agg(
    Total_Revenue=("Revenue", "sum"),
    Total_Units=("Units", "sum"),
    Num_Orders=("Product", "count"),
).reset_index()
print("\nRevenue by Region:")
display(region_summary)

Original DataFrame:

    Product Region  Units  Price Month   Revenue
0  Widget A  North    120  29.99   Jan   3598.80
1  Widget B  South     85  49.95   Jan   4245.75
2  Gadget X  North    200  99.00   Jan  19800.00
3  Gadget Y   East    150  79.50   Feb  11925.00
4  Widget A   East     95  29.99   Feb   2849.05
5  Gadget X  South    175  99.00   Feb  17325.00

Revenue by Region:

  Region  Total_Revenue  Total_Units  Num_Orders
0   East       14774.05          245           2
1  North       23398.80          320           2
2  South       21570.75          260           2

In [32]:

# Group by Month + Product — total revenue
monthly = df.groupby(["Month", "Product"])["Revenue"].sum().reset_index()
monthly.columns = ["Month", "Product", "Revenue"]
print("\nRevenue by Month & Product:")
display(monthly)

Revenue by Month & Product:

  Month   Product   Revenue
0   Feb  Gadget X  17325.00
1   Feb  Gadget Y  11925.00
2   Feb  Widget A   2849.05
3   Jan  Gadget X  19800.00
4   Jan  Widget A   3598.80
5   Jan  Widget B   4245.75

In [33]:

# Pivot table — Revenue: rows=Region, columns=Month
pivot = pd.pivot_table(df,
                       values="Revenue",
                       index="Region",
                       columns="Month",
                       aggfunc="sum",
                       fill_value=0)
print("\nPivot Table (Revenue):")
display(pivot)

Pivot Table (Revenue):

Month        Feb       Jan
Region
East    14774.05      0.00
North       0.00  23398.80
South   17325.00   4245.75

## 9. NumPy ↔ Pandas Integration

Pandas is built on top of NumPy. Conversion between the two is seamless:

| Direction | Method |
|-----------|--------|
| DataFrame → ndarray | `df.values` or `df.to_numpy()` |
| ndarray → DataFrame | `pd.DataFrame(arr, columns=...)` |
| Apply NumPy ufunc on column | `np.log(df["col"])` |

In [39]:
# 1. DataFrame → NumPy
numeric_df = df[["Units", "Price", "Revenue"]]
arr_from_df = numeric_df.to_numpy()
print("DataFrame → ndarray:")
print(arr_from_df)
print("Type:", type(arr_from_df), "| Shape:", arr_from_df.shape)

DataFrame → ndarray:
[[  120.      29.99  3598.8 ]
 [   85.      49.95  4245.75]
 [  200.      99.   19800.  ]
 [  150.      79.5  11925.  ]
 [   95.      29.99  2849.05]
 [  175.      99.   17325.  ]]
Type: <class 'numpy.ndarray'> | Shape: (6, 3)

In [36]:

# 2. NumPy → DataFrame
data_np = np.array([
    [101, 5.5, 250.0],
    [102, 6.2, 310.0],
    [103, 4.8, 200.0],
])
df_from_np = pd.DataFrame(data_np, columns=["ID", "Weight_kg", "Value"])
print("\nndarray → DataFrame:")
display(df_from_np)

ndarray → DataFrame:

      ID  Weight_kg  Value
0  101.0        5.5  250.0
1  102.0        6.2  310.0
2  103.0        4.8  200.0

In [37]:

# 3. Apply NumPy ufuncs directly on Pandas columns
df["Log_Revenue"]    = np.log(df["Revenue"])
df["Sqrt_Units"]     = np.sqrt(df["Units"])
df["Revenue_Scaled"] = (df["Revenue"] - df["Revenue"].mean()) / df["Revenue"].std()
print("\nDataFrame with NumPy-derived columns:")
display(df[["Product", "Revenue", "Log_Revenue", "Sqrt_Units", "Revenue_Scaled"]].round(3))

DataFrame with NumPy-derived columns:

    Product   Revenue  Log_Revenue  Sqrt_Units  Revenue_Scaled
0  Widget A   3598.80        8.188      10.954          -0.852
1  Widget B   4245.75        8.354       9.220          -0.765
2  Gadget X  19800.00        9.893      14.142           1.319
3  Gadget Y  11925.00        9.386      12.247           0.264
4  Widget A   2849.05        7.955       9.747          -0.952
5  Gadget X  17325.00        9.760      13.229           0.987

In [38]:

# 4. NumPy operations on a column
print("\nCorrelation (np.corrcoef) between Units and Revenue:",
      np.corrcoef(df["Units"], df["Revenue"])[0, 1].round(4))

print("\n--- Demo complete! ---")

Correlation (np.corrcoef) between Units and Revenue: 0.96

--- Demo complete! ---